In [1]:
import numpy as np

In [2]:
"""
List to Array
np.copy()
fromfunction()  --> objecive is to generate a n-D Array
fromiter()
fromstring("", sep = "", dtype = )
ndim/shape/size
np.arange(start, end, step_Value)
np.linspace()
np.zeros()
np.ones()
np.empty() --> Some Random data is returned
np.eye()
np.logspace()
np.reshape()
np.random.rand()
np.random.randn()
np.random.randint()
np.dot
np.log
np.exp

"""

'\nList to Array\nnp.copy()\nfromfunction()  --> objecive is to generate a n-D Array\nfromiter()\nfromstring("", sep = "", dtype = )\nndim/shape/size\nnp.arange(start, end, step_Value)\nnp.linspace()\nnp.zeros()\nnp.ones()\nnp.empty() --> Some Random data is returned\nnp.eye()\nnp.logspace()\nnp.reshape()\nnp.random.rand()\nnp.random.randn()\nnp.random.randint()\nnp.dot\nnp.log\nnp.exp\n\n'

In [3]:
import array

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
type(np.array([1,2,3,4,5])) # 1-D Array

numpy.ndarray

In [8]:
np.array([1,2,3,4.0,5.2]) # upcasts all the elements by default.

array([1. , 2. , 3. , 4. , 5.2])

In [9]:
np.array([[1,2,3], [4,5,6]
         ])

# 2-D Array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.array([ [1,2], [1,2,3], [1,2,3,4]
         ]
)

<ipython-input-10-070d79845d96>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([ [1,2], [1,2,3], [1,2,3,4]


array([list([1, 2]), list([1, 2, 3]), list([1, 2, 3, 4])], dtype=object)

In [11]:
np.array([
    [
        [1,2,3], [4,5,6]
        
    ], 
    [
        [7,8,9], [10,11,12]
    ]
    
    
])

# 3-D Array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
np.array([1,2,3], dtype = complex)  # Type Conversion 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [15]:
arr = np.array([
    [1,2,3], [4,5,6]
])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr[0]

array([1, 2, 3])

In [18]:
arr[1]

array([4, 5, 6])

In [19]:
arr[0][0]

1

In [20]:
arr[0][1]

2

In [21]:
arr[1][0]

4

In [22]:
arr[1][1]

5

In [23]:
type(arr[1][1])

numpy.int32

In [24]:
mat = np.matrix(arr) # Matrix form of the Array.

In [35]:
l = [1,2,3,4,5,88] #List to Array Conversion

In [36]:
np.array(l)

array([ 1,  2,  3,  4,  5, 88])

In [38]:
'''
Input data: in any form that can be converted to an array. 
    This includes lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.
    
Output: ndarray
'''
np.asarray(l)

array([ 1,  2,  3,  4,  5, 88])

In [39]:
'''
Convert the input to an ndarray, but pass ndarray subclasses through.
'''

np.asanyarray(l)

array([ 1,  2,  3,  4,  5, 88])

In [40]:
np.array(arr) 

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.asanyarray(mat) # Here mat is already in array format. Hence,no  type conversion operation will be invoked.

matrix([[1, 2, 3],
        [4, 5, 6]])

In [41]:
a = arr # Shallow Copy --> Memory Location of a and arr is same. Hence, any changes made to arr will be reflcted to a

In [42]:
b = np.copy(arr) # Deep Copy

In [43]:
arr[0][1] = 123

In [44]:
arr

array([[  1, 123,   3],
       [  4,   5,   6]])

In [45]:
a

array([[  1, 123,   3],
       [  4,   5,   6]])

In [46]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# Construct an array by executing a function over each coordinate.

np.fromfunction(lambda i, j: i==j, (4,4))  # Generated n-D Array based on given condition

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [48]:
np.fromfunction(lambda i, j: i/j, (3,3))  # numpy treats 0/0 --> Nan   1/0 --> inf

<ipython-input-48-d3d34a77ba3a>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i/j, (3,3))  # numpy treats 0/0 --> Nan   1/0 --> inf
<ipython-input-48-d3d34a77ba3a>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i/j, (3,3))  # numpy treats 0/0 --> Nan   1/0 --> inf


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [49]:
gen_obj = (i * i for i in range(5)) # Generator object if tuple is used instead of list comprehension.

In [50]:

# Create a new 1-dimensional array from an iterable object.

np.fromiter(gen_obj, dtype = int)

array([ 0,  1,  4,  9, 16])

In [38]:
np.fromstring("1,2,3,4,5", sep = ',',dtype=int)

array([1, 2, 3, 4, 5])

In [51]:
arr

array([[  1, 123,   3],
       [  4,   5,   6]])

In [52]:

arr.ndim # Dimension of an array

2

In [53]:
arr.size # No of elements in the given array

6

In [54]:
arr.shape # 2 rows and 3 columns

(2, 3)

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr2 = np.array([
    [
        [1,2,3],
        [4,5,6],
    ],
      [
        [7,8,9],
        [10,11,12],
    ]
    
    
    
])

In [57]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr2.ndim

3

In [59]:
arr2.shape

(2, 2, 3)

In [60]:
arr2.size

12

In [61]:
# range(5.5)
# Since Range takes only integer values as its arguments

In [62]:
# So we have a new function in the np library to support the above condition
'''
Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.
'''
np.arange(4)

array([0, 1, 2, 3])

In [63]:
np.arange(3.4)

array([0., 1., 2., 3.])

In [64]:
np.arange(4, 5, 0.2) # Start Value, End Value, Step COUNT
# If the Value is float then END Point is also returned to the output stream

array([4. , 4.2, 4.4, 4.6, 4.8])

In [65]:
np.arange(4, 5, -1) # Start Vaue, End value, Negative Count

array([], dtype=int32)

In [66]:
type(np.arange(9, 5, -.2) )# Works since end value is lesser than the start value. (Here step count is negative)

numpy.ndarray

In [72]:
np.arange(9,5, -0.2)

array([9. , 8.8, 8.6, 8.4, 8.2, 8. , 7.8, 7.6, 7.4, 7.2, 7. , 6.8, 6.6,
       6.4, 6.2, 6. , 5.8, 5.6, 5.4, 5.2])

In [74]:
np.arange(1,5)

array([1, 2, 3, 4])

In [75]:
np.arange(2,3,0.2, dtype='float')

array([2. , 2.2, 2.4, 2.6, 2.8])

In [79]:

'''
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].
'''
np.linspace(1, 5, 3)

array([1., 3., 5.])

In [80]:
np.linspace(2, 10, 4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [81]:
np.linspace(1, 10) # Default size is 50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [82]:
np.linspace(1,5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [83]:
np.linspace(1, 5, 4, endpoint=False)

array([1., 2., 3., 4.])

In [84]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [85]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [91]:
'''
Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
'''

np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
np.zeros([2,3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [92]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [95]:
'''
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints

'''

np.ones(5)

array([1., 1., 1., 1., 1.])

In [96]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
np.ones((3, 4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [99]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [101]:
np.empty((4,3))

array([[1.47365388e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.75983079e+164],
       [5.49607224e-090, 7.86493303e-067, 2.81268057e-033],
       [2.25168957e+184, 3.99910963e+252, 3.44128730e+175]])

In [103]:
np.eye(5, dtype = int) # Returns Identity  Matrix of the given size.

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [104]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [105]:
(np.linspace(1,100, 50))

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [106]:
data = np.linspace(4,7, num=40)

In [107]:
data

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [108]:
data.ndim

1

In [109]:
data.shape

(40,)

In [110]:
data.reshape(40,1) # Rows = 40, Columns =1

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [111]:
data.reshape(2, 1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [112]:
 #  Create an array of the given shape and populate it with random samples from a uniform distribution (0,1)
np.random.rand(5)

array([0.48211617, 0.92631232, 0.62361751, 0.421162  , 0.37714613])

In [113]:
np.random.randn(5) # Standard Normal Distribution values.

array([ 1.36687099,  0.36437616, -2.43133019,  0.77108451,  1.7710639 ])

In [114]:
np.random.randn(5,3)

array([[ 0.0884252 ,  0.38535857,  0.36203598],
       [ 0.58384463,  1.1236663 ,  0.87827685],
       [-0.91709902, -0.90746618,  0.42122711],
       [ 1.05286762, -0.44141268,  1.40728296],
       [-0.9407255 ,  0.15907716,  0.09106428]])

In [115]:

#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1, 5)

3

In [116]:
np.random.randint(1,10, (4,4))

array([[2, 6, 8, 5],
       [2, 3, 8, 9],
       [4, 3, 7, 3],
       [2, 9, 5, 8]])

In [117]:
arr = np.random.randint(3,9, (3,3))

In [118]:
arr

array([[7, 3, 5],
       [3, 7, 8],
       [7, 8, 5]])

In [119]:
arr.size

9

In [120]:
arr.reshape(1,9)

array([[7, 3, 5, 3, 7, 8, 7, 8, 5]])

In [121]:
arr.reshape(9,1)

array([[7],
       [3],
       [5],
       [3],
       [7],
       [8],
       [7],
       [8],
       [5]])

In [122]:
arr.reshape(1,1,9)

array([[[7, 3, 5, 3, 7, 8, 7, 8, 5]]])

In [123]:
arr.reshape(3,3,1)

array([[[7],
        [3],
        [5]],

       [[3],
        [7],
        [8]],

       [[7],
        [8],
        [5]]])

In [124]:
arr.reshape(1,-1)

array([[7, 3, 5, 3, 7, 8, 7, 8, 5]])

In [125]:
arr.reshape(3, -1)

array([[7, 3, 5],
       [3, 7, 8],
       [7, 8, 5]])

In [126]:
arr = np.random.randint(2,100, (5,5))

In [127]:
arr

array([[ 2, 14, 68, 41, 29],
       [42, 34, 29, 74, 74],
       [ 9, 14, 75, 21, 58],
       [65, 51, 27, 22, 72],
       [11, 87, 21,  3, 63]])

In [128]:
arr[3:, 3:]

array([[22, 72],
       [ 3, 63]])

In [129]:
arr[:, [1,3]]

array([[14, 41],
       [34, 74],
       [14, 21],
       [51, 22],
       [87,  3]])

In [130]:
arr > 9

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [131]:
arr2 = np.random.randint(2, 100, (5,5))

In [132]:
arr2

array([[84, 72,  6, 56, 33],
       [92, 26, 16, 11, 50],
       [35, 44, 78, 11, 90],
       [74, 37, 49, 47,  6],
       [77, 90, 98, 87, 77]])

In [133]:

# Index based Multiplication
arr * arr2

array([[ 168, 1008,  408, 2296,  957],
       [3864,  884,  464,  814, 3700],
       [ 315,  616, 5850,  231, 5220],
       [4810, 1887, 1323, 1034,  432],
       [ 847, 7830, 2058,  261, 4851]])

In [134]:
# Matrix Multiplication
arr @arr2

array([[ 9103,  7627, 10391,  5464,  9365],
       [18845, 14582, 13936, 12961, 11838],
       [10689, 10309, 12841,  7516, 12339],
       [18269, 14488, 11446, 11796, 12801],
       [14736,  9759,  9417,  7426, 11472]])

In [135]:
arr1 = np.zeros((3,4), dtype = int)

In [136]:
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [137]:
# ROW Wise Broadcasting
arr1 + [1,2,3,4]

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [138]:

# Column Wise Broadcasting.

np.array([1,2,3]).reshape(3, 1) + arr1

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [139]:
arr2.T # Transpose of the given matrix.


array([[84, 92, 35, 74, 77],
       [72, 26, 44, 37, 90],
       [ 6, 16, 78, 49, 98],
       [56, 11, 11, 47, 87],
       [33, 50, 90,  6, 77]])

In [140]:
np.exp(arr2)

array([[3.02507732e+36, 1.85867175e+31, 4.03428793e+02, 2.09165950e+24,
        2.14643580e+14],
       [9.01762841e+39, 1.95729609e+11, 8.88611052e+06, 5.98741417e+04,
        5.18470553e+21],
       [1.58601345e+15, 1.28516001e+19, 7.49841700e+33, 5.98741417e+04,
        1.22040329e+39],
       [1.37338298e+32, 1.17191424e+16, 1.90734657e+21, 2.58131289e+20,
        4.03428793e+02],
       [2.75851345e+33, 1.22040329e+39, 3.63797095e+42, 6.07603023e+37,
        2.75851345e+33]])

In [141]:
np.sqrt(arr2)

array([[9.16515139, 8.48528137, 2.44948974, 7.48331477, 5.74456265],
       [9.59166305, 5.09901951, 4.        , 3.31662479, 7.07106781],
       [5.91607978, 6.63324958, 8.83176087, 3.31662479, 9.48683298],
       [8.60232527, 6.08276253, 7.        , 6.8556546 , 2.44948974],
       [8.77496439, 9.48683298, 9.89949494, 9.32737905, 8.77496439]])

In [142]:
np.log10(arr2)

array([[1.92427929, 1.8573325 , 0.77815125, 1.74818803, 1.51851394],
       [1.96378783, 1.41497335, 1.20411998, 1.04139269, 1.69897   ],
       [1.54406804, 1.64345268, 1.8920946 , 1.04139269, 1.95424251],
       [1.86923172, 1.56820172, 1.69019608, 1.67209786, 0.77815125],
       [1.88649073, 1.95424251, 1.99122608, 1.93951925, 1.88649073]])

In [145]:
np.random.seed(10)

In [146]:
np.random.randn(3,3)

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143]])